// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_GALLERY_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_GALLERY_DAT_H

extern SPRT_DAT gallery_tex[118];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_GALLERY_DAT_H
