// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_LANG_SL_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_LANG_SL_DAT_H

extern SPRT_DAT lang_sl_tex[17];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_LANG_SL_DAT_H
