// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_MISSION_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_MISSION_DAT_H

extern SPRT_DAT mission_tex[174];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_MISSION_DAT_H
