// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_OUTGAME_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_OUTGAME_DAT_H

extern SPRT_DAT out_game_tex[8];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_OUTGAME_DAT_H
