// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_SETUP_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_SETUP_DAT_H

extern SPRT_DAT setup_tex[55];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_TIM_DAT_SETUP_DAT_H
