// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MAP_MAP_REVERB_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MAP_MAP_REVERB_H


void map_reverbInit();
void map_reverbAfterMCLoadInit();
void map_reverbMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MAP_MAP_REVERB_H
