// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H

float copysignf(float x, float y);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_COPYSIGN_H
