// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H

int finitef(float x);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_FINITE_H
