// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H


float scalbnf(float x, int n);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_COMMON_SF_SCALBN_H
