// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ENEMY_ENEMY_ACT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ENEMY_ENEMY_ACT_H

typedef union {
	u_char *pu8;
	u_short *pu16;
	u_int *pu32;
	u_long *pu64;
	char *ps8;
	short int *ps16;
	int *ps32;
	long int *ps64;
	long int wrk;
} P_INT;

struct ENEALG_WRK {
	long int comm_add_top;
	u_long stack_b[16];
	u_long *stack_p;
	long int bcomm_add_top;
	P_INT bcomm_add;
	P_INT comm_add;
	float wait_time;
	float loop[2];
	float loop_tr[2];
	float bwait_time;
	u_char pos_no_tr[2];
	u_char cnt[2];
	u_char idx;
	u_char job_no;
	u_char pos_no;
	u_char flag;
	u_char branch;
	u_char bjob_no;
	u_char bpos_no;
};

extern int debug_alg;
extern void (*CommJmpContTbl[74])(/* parameters unknown */);
extern void (*CommJmpMoveTbl[22])(/* parameters unknown */);
extern void (*CommJmpBrnchTbl[43])(/* parameters unknown */);
extern void (*CommJmpEffTbl[6])(/* parameters unknown */);
extern void (*BCommJmpTbl[8])(/* parameters unknown */);
extern unsigned char ENE_WRK type_info node[8];

void EneAlgCtrl(ENE_WRK *ew);
void EneBlinkCtrl(ENE_WRK *ew);
void EJobC00(ENEALG_WRK *alg);
void EJobC01(ENEALG_WRK *alg);
void EJobC02(ENEALG_WRK *alg);
void EJobC03(ENEALG_WRK *alg);
void EJobC04(ENEALG_WRK *alg);
void EJobC05(ENEALG_WRK *alg);
void EJobC06(ENEALG_WRK *alg);
void EJobC07(ENEALG_WRK *alg);
void EJobC08(ENEALG_WRK *alg);
void EJobC09(ENEALG_WRK *alg);
void EJobC0A(ENEALG_WRK *alg);
void EJobC0B(ENEALG_WRK *alg);
void EJobC0C(ENEALG_WRK *alg);
void EJobC0D(ENEALG_WRK *alg);
void EJobC0E(ENEALG_WRK *alg);
void EJobC0F(ENEALG_WRK *alg);
void EJobC10(ENEALG_WRK *alg);
void EJobC11(ENEALG_WRK *alg);
void EJobC12(ENEALG_WRK *alg);
void EJobC13(ENEALG_WRK *alg);
void EJobC14(ENEALG_WRK *alg);
void EJobC15(ENEALG_WRK *alg);
void EJobC16(ENEALG_WRK *alg);
void EJobC17(ENEALG_WRK *alg);
void EJobC18(ENEALG_WRK *alg);
void EJobC19(ENEALG_WRK *alg);
void EJobC1A(ENEALG_WRK *alg);
void EJobC1B(ENEALG_WRK *alg);
void EJobC1C(ENEALG_WRK *alg);
void EJobC1D(ENEALG_WRK *alg);
void EJobC1E(ENEALG_WRK *alg);
void EJobC1F(ENEALG_WRK *alg);
void EJobC20(ENEALG_WRK *alg);
void EJobC21(ENEALG_WRK *alg);
void EJobC22(ENEALG_WRK *alg);
void EJobC23(ENEALG_WRK *alg);
void EJobC24(ENEALG_WRK *alg);
void EJobC25(ENEALG_WRK *alg);
void EJobC26(ENEALG_WRK *alg);
void EJobC27(ENEALG_WRK *alg);
void EJobC28(ENEALG_WRK *alg);
void EJobC29(ENEALG_WRK *alg);
void EJobC2A(ENEALG_WRK *alg);
void EJobC2B(ENEALG_WRK *alg);
void EJobC2C(ENEALG_WRK *alg);
void EJobC2D(ENEALG_WRK *alg);
void EJobC2E(ENEALG_WRK *alg);
void EJobC2F(ENEALG_WRK *alg);
void EJobC30(ENEALG_WRK *alg);
void EJobC31(ENEALG_WRK *alg);
void EJobC32(ENEALG_WRK *alg);
void EJobC33(ENEALG_WRK *alg);
void EJobC34(ENEALG_WRK *alg);
void EJobC35(ENEALG_WRK *alg);
void EJobC36(ENEALG_WRK *alg);
void EJobC37(ENEALG_WRK *alg);
void EJobC38(ENEALG_WRK *alg);
void EJobC39(ENEALG_WRK *alg);
void EJobC3A(ENEALG_WRK *alg);
void EJobC3B(ENEALG_WRK *alg);
void EJobC3C(ENEALG_WRK *alg);
void EJobC3D(ENEALG_WRK *alg);
void EJobC3E(ENEALG_WRK *alg);
void EJobC3F(ENEALG_WRK *alg);
void EJobC40(ENEALG_WRK *alg);
void EJobC41(ENEALG_WRK *alg);
void EJobC42(ENEALG_WRK *alg);
void EJobC43(ENEALG_WRK *alg);
void EJobC44(ENEALG_WRK *alg);
void EJobC45(ENEALG_WRK *alg);
void EJobC46(ENEALG_WRK *alg);
void EJobC47(ENEALG_WRK *alg);
void EJobC48(ENEALG_WRK *alg);
void EJobC49(ENEALG_WRK *alg);
void EJobM00(ENEALG_WRK *alg);
void EJobM01(ENEALG_WRK *alg);
void EJobM02(ENEALG_WRK *alg);
void EJobM03(ENEALG_WRK *alg);
void EJobM04(ENEALG_WRK *alg);
void EJobM05(ENEALG_WRK *alg);
void EJobM06(ENEALG_WRK *alg);
void EJobM07(ENEALG_WRK *alg);
void EJobM08(ENEALG_WRK *alg);
void EJobM09(ENEALG_WRK *alg);
void EJobM0A(ENEALG_WRK *alg);
void EJobM0B(ENEALG_WRK *alg);
void EJobM0C(ENEALG_WRK *alg);
void EJobM0D(ENEALG_WRK *alg);
void EJobM0E(ENEALG_WRK *alg);
void EJobM0F(ENEALG_WRK *alg);
void EJobM10(ENEALG_WRK *alg);
void EJobM11(ENEALG_WRK *alg);
void EJobM12(ENEALG_WRK *alg);
void EJobM13(ENEALG_WRK *alg);
void EJobM14(ENEALG_WRK *alg);
void EJobM15(ENEALG_WRK *alg);
void EJobB00(ENEALG_WRK *alg);
void EJobB01(ENEALG_WRK *alg);
void EJobB02(ENEALG_WRK *alg);
void EJobB03(ENEALG_WRK *alg);
void EJobB04(ENEALG_WRK *alg);
void EJobB05(ENEALG_WRK *alg);
void EJobB06(ENEALG_WRK *alg);
void EJobB07(ENEALG_WRK *alg);
void EJobB08(ENEALG_WRK *alg);
void EJobB09(ENEALG_WRK *alg);
void EJobB0A(ENEALG_WRK *alg);
void EJobB0B(ENEALG_WRK *alg);
void EJobB0C(ENEALG_WRK *alg);
void EJobB0D(ENEALG_WRK *alg);
void EJobB0E(ENEALG_WRK *alg);
void EJobB0F(ENEALG_WRK *alg);
void EJobB10(ENEALG_WRK *alg);
void EJobB11(ENEALG_WRK *alg);
void EJobB12(ENEALG_WRK *alg);
void EJobB13(ENEALG_WRK *alg);
void EJobB14(ENEALG_WRK *alg);
void EJobB15(ENEALG_WRK *alg);
void EJobB16(ENEALG_WRK *alg);
void EJobB17(ENEALG_WRK *alg);
void EJobB18(ENEALG_WRK *alg);
void EJobB19(ENEALG_WRK *alg);
void EJobB1A(ENEALG_WRK *alg);
void EJobB1B(ENEALG_WRK *alg);
void EJobB1C(ENEALG_WRK *alg);
void EJobB1D(ENEALG_WRK *alg);
void EJobB1E(ENEALG_WRK *alg);
void EJobB1F(ENEALG_WRK *alg);
void EJobB20(ENEALG_WRK *alg);
void EJobB21(ENEALG_WRK *alg);
void EJobB22(ENEALG_WRK *alg);
void EJobB23(ENEALG_WRK *alg);
void EJobB24(ENEALG_WRK *alg);
void EJobB25(ENEALG_WRK *alg);
void EJobB26(ENEALG_WRK *alg);
void EJobB27(ENEALG_WRK *alg);
void EJobB28(ENEALG_WRK *alg);
void EJobB29(ENEALG_WRK *alg);
void EJobB2A(ENEALG_WRK *alg);
void EJobE00(ENEALG_WRK *alg);
void EJobE01(ENEALG_WRK *alg);
void EJobE02(ENEALG_WRK *alg);
void EJobE03(ENEALG_WRK *alg);
void EJobE04(ENEALG_WRK *alg);
void EJobE05(ENEALG_WRK *alg);
void BJobL00(ENE_WRK *ew);
void BJobL01(ENE_WRK *ew);
void BJobL02(ENE_WRK *ew);
void BJobL03(ENE_WRK *ew);
void BJobL04(ENE_WRK *ew);
void BJobL05(ENE_WRK *ew);
void BJobL06(ENE_WRK *ew);
void SetEnemyParallelLight(ENE_WRK *ew, float r, float g, float b, float amb);
ENE_WRK* ENE_WRK * _fixed_array_verifyrange<ENE_WRK>(size_t v, size_t _max);
type_info& ENE_WRK type_info function();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ENEMY_ENEMY_ACT_H
