// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_DOOR_DAT_DOOR_LOCK_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_DOOR_DAT_DOOR_LOCK_DAT_H

typedef struct {
	int msg_id;
	int sound_id;
} DOOR_LOCK_INFO;

extern DOOR_LOCK_INFO door_lock_info[7];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_DOOR_DAT_DOOR_LOCK_DAT_H
