// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_DRAW_LINE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_DRAW_LINE_H

void DrawCmnLine(float x, float y, float size, u_char type, u_char alp, u_int pri);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_DRAW_LINE_H
