// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DEF_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DEF_DAT_H

typedef struct {
	int x;
	int y;
} MSG_DEF_DATA;

extern MSG_DEF_DATA msg_def_data[4];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DEF_DAT_H
