// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DISP_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DISP_DAT_H

typedef struct {
	int msg_def_id;
	int msg_win_id;
} MSG_DISP_DATA;

extern MSG_DISP_DATA msg_disp_data[83];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_DISP_DAT_H
