// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_COL_TBL_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_COL_TBL_H

typedef struct {
	u_char r;
	u_char g;
	u_char b;
} MSG_COLOR;

extern MSG_COLOR msg_col[45];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_MSG_COL_TBL_H
