// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_BTN_SPRT_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_BTN_SPRT_DAT_H

extern SPRT_DAT btn_tex[15];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_BTN_SPRT_DAT_H
