// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_CAPTION_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_CAPTION_DAT_H

extern SPRT_DAT caption_tex[17];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_CAPTION_DAT_H
