// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_MSG_BOX_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_MSG_BOX_H

extern SPRT_DAT msg_box_tex[12];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH2D_TIM_DAT_MSG_BOX_H
