// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_FILE_TEX_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_FILE_TEX_DAT_H

extern int file_tex_pack[2];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_FILE_TEX_DAT_H
