// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_GHOST_SEAL_DOOR_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_GHOST_SEAL_DOOR_DAT_H

typedef struct {
	int end_room_label;
	float pos_x;
	float pos_y;
} GHOST_SEAL_DOOR_DATA;

extern GHOST_SEAL_DOOR_DATA ghost_seal_door_data[9];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_TIM_DAT_GHOST_SEAL_DOOR_DAT_H
