// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_EEEXCEPTION_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_EEEXCEPTION_H

typedef enum {
	PS2E_INTERRUPT = 0,
	PS2E_TLB_MOD = 1,
	PS2E_TLB_LOAD_OR_IFETCH = 2,
	PS2E_TLB_STORE = 3,
	PS2E_ADDRESS_ERROR_LOAD_OR_IFETCH = 4,
	PS2E_ADDRESS_ERROR_STORE = 5,
	PS2E_BUS_ERROR_IFETCH = 6,
	PS2E_BUS_ERROR_DATAREF_LOAD_OR_STORE = 7,
	PS2E_SYSCALL = 8,
	PS2E_BREAKPOINT = 9,
	PS2E_RESERVED_INSTRUCTION = 10,
	PS2E_COP_UNUSABLE = 11,
	PS2E_ARITHMETIC_OVERFLOW = 12,
	PS2E_TRAP = 13,
	NUM_PS2EXCEPTION = 14
} PS2EXCEPTION;

struct IOPEXCEPTIONCREATIONDATA {
	char *pModuleName;
};


void _IOPExceptionHandler();
void eeexceptionInitialize();
void eeexceptionEnableExcCode(PS2EXCEPTION eee, int bEnable);
void eeexceptionEnableExcCodeAll(int bEnable);
void iopexceptionInitialize(IOPEXCEPTIONCREATIONDATA *pCD);
void _strcatf(char *strDest, char *pStr);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_EEEXCEPTION_H
