// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_G3DVU0INSTANCE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_G3DVU0INSTANCE_H

typedef void (*LPFUNC_VU0LOADMATRIX)(/* parameters unknown */);
typedef void (*LPFUNC_VU0APPLYMATRIXWITHOUTTRANS)(/* parameters unknown */);
extern LPFUNC_VU0LOADMATRIX CVu0Matrix::s_pFuncLoadMatrix;
extern LPFUNC_VU0APPLYMATRIXWITHOUTTRANS CVu0Matrix::s_pFuncApplyMatrixWithoutTrans;


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_GRAPH3D_G3DVU0INSTANCE_H
