// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H


float __ieee754_acosf(float x);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ACOS_H
