// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H


float __ieee754_atan2f(float y, float x);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_ATAN2_H
