// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H


float __ieee754_powf(float x, float y);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_EF_POW_H
