// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H

int isnanf(float x);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_SF_ISNAN_H
