// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H

float sqrtf(float x);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBM_MATH_WF_SQRT_H
