// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_FSTATR_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_FSTATR_H

int _fstat_r(_reent *ptr, int fd, stat *pstat);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_FSTATR_H
