// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H

extern _reent *_impure_ptr;


#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_REENT_IMPURE_H
