// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MOVIE_ROOM_MENU_PRG_MOVIE_ROOM_MENU_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MOVIE_ROOM_MENU_PRG_MOVIE_ROOM_MENU_H


void MovieRoomMenuInit();
int MovieRoomMenuMain();
void MovieRoomMenuEnd();
void MovieRoomMenuDisp();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MOVIE_ROOM_MENU_PRG_MOVIE_ROOM_MENU_H
