// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_DEBUG_ITEM_DEBUG_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_DEBUG_ITEM_DEBUG_H

void ItemDbg_PlyrItemLink();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_DEBUG_ITEM_DEBUG_H
