// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_LOADING_LOADING_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_LOADING_LOADING_DAT_H

extern SPRT_DAT loading_tex[5];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_LOADING_LOADING_DAT_H
