// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_COMMON_FILEST_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_COMMON_FILEST_H


int FileStGetType(int label_id);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_COMMON_FILEST_H
