// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ITEM_DAT_ITEM_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ITEM_DAT_ITEM_DAT_H

extern ITEM_DAT item_dat[58];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_ITEM_DAT_ITEM_DAT_H
