// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_MC_CHECK_EMPTY_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_MC_CHECK_EMPTY_H

int MemoryCardCheckEmpty(int dir_label);
int MemoryCardCheckEmptyBroken(int dir_label);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_MC_CHECK_EMPTY_H
