// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_PC_SAVE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_PC_SAVE_H

void SavePCFile();
void LoadPCFile();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_SYSTEM_MC_PRG_PC_SAVE_H
