// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_H


void PauseInit();
int PauseMain();
void PauseDispMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_H
