// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_DAT_H

extern SPRT_DAT pause_tex[9];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PAUSE_PRG_PAUSE_DAT_H
