// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_AUTOLOAD_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_AUTOLOAD_H


void init_AutoLoad_Main();
GPHASE_ENUM one_AutoLoad_Main(GPHASE_ENUM dummy);
void end_AutoLoad_Main();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_AUTOLOAD_H
