// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_FRAMERATE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_FRAMERATE_H

void FrameRateSelMain();
void FrameRateSelDispMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_FRAMERATE_H
