// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_GALLERY_DISP_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_GALLERY_DISP_H

int GalAnimation();
void GalleryDispTop();
void GalleryDispView();
void GalleryDispMovie();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_GALLERY_DISP_H
