// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_LANG_CHECK_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_LANG_CHECK_H


void init_LangData_Check();
GPHASE_ENUM one_LangData_Check(GPHASE_ENUM dummy);
void end_LangData_Check();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_LANG_CHECK_H
