// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_MISSION_PAUSE_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_MISSION_PAUSE_H


void MisPauseInit();
int MisPauseMain();
void MisPauseDispMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_OUTGAME_MISSION_PAUSE_H
