// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_MENU_CAM_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_MENU_CAM_H

void MenuCam();
void MenuCamDisp();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_MENU_MENU_CAM_H
