// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_GAMECLEAR_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_GAMECLEAR_DAT_H

extern SPRT_DAT gameclear_tex[50];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_GAMECLEAR_DAT_H
