// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_RANK_TIME_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_RANK_TIME_DAT_H

extern int rank_time_tbl[7][3];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_CLEAR_DAT_RANK_TIME_DAT_H
