// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_OUT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_OUT_H


void SavePointFadeOutInit();
void SavePointFadeOutDispMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_OUT_H
