// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_IN_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_IN_H


void SavePointFadeInCtrlInit();
void SavePointFadeInMain();
void SavePointFadeInDispMain();

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_SAVEPOINT_SAVEPOINT_FADE_IN_H
