// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H

extern char _ctype_[257];


#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_CTYPE_CTYPE__H
