// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PLYR_CHARBB_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PLYR_CHARBB_H


int charbbGet(float *avBB[4], ANI_CTRL *pAC, float *matLocalWorld[4]);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PLYR_CHARBB_H
