// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PHOTO_N_FINDER_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PHOTO_N_FINDER_DAT_H

extern SPRT_DAT n_finder_dat[168];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PHOTO_N_FINDER_DAT_H
