// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_ACS_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_ACS_DAT_H

struct SPHERE {
	sceVu0FVECTOR center;
	float r;
};

struct TUBE {
	sceVu0FVECTOR p0;
	sceVu0FVECTOR p1;
	float r;
	u_int axis;
};

struct CPLANE {
	sceVu0FVECTOR p0;
	float r;
};

struct COLLISION_DAT {
	void *dat;
	u_char type;
	u_char bone_id;
};

struct ROPE_DAT {
	float *vtx;
	float gravity;
	float Kd;
	float Ke;
	u_int fixed_num;
};

struct CLOTH {
	float gravity;
	float Kd;
	float Ke;
	u_char w;
	u_char h;
	u_char type;
};

struct CLOTH_DAT {
	CLOTH *dat;
	sceVu0FVECTOR *rist_vtx;
	u_char bone_id;
	u_char bone_id2;
	u_char sgd_id;
	u_char flg;
	int b_point;
};

struct WMIM {
	u_char *name;
	float mass;
	float Ks;
	float dec;
	sceVu0FVECTOR pos;
	sceVu0FVECTOR gravity;
};

struct WMIM_DAT {
	WMIM *dat;
	u_char bone_id;
};

extern SPHERE sphere_R35;
extern SPHERE sphere_R50;
extern SPHERE sphere_R70;
extern SPHERE sphere_R100;
extern SPHERE sphere_R150;
extern SPHERE sphere_R200;
extern TUBE tube_R150_H200;
extern TUBE tube_R90_H200;
extern SPHERE sphere_mio;
extern SPHERE sphere_hako;
extern TUBE tube_momol_mio;
extern TUBE tube_momor_mio;
extern SPHERE sphere_face;
extern SPHERE sphere_rakka;
extern SPHERE sphere_kubiore;
extern TUBE tube_waningyou_head;
extern TUBE tube_waningyou;
extern TUBE tube_up_leg_l;
extern TUBE tube_low_leg_l;
extern TUBE tube_up_leg_r;
extern TUBE tube_low_leg_r;
extern TUBE tube_momol;
extern TUBE tube_momor;
extern TUBE tube_momo_sae;
extern CPLANE plane_floor;
extern CPLANE plane_ituki;
extern WMIM mimacs_hair_dat0;
extern WMIM_DAT ch000_wmim_tbl[2];
extern WMIM mimacs_hair_dat1;
extern WMIM_DAT ch001_wmim_tbl[2];
extern WMIM mimacs_hair_dat3;
extern WMIM_DAT ch003_wmim_tbl[2];
extern WMIM mimacs_hair_dat17;
extern WMIM_DAT ch017_wmim_tbl[2];
extern WMIM mimacs_hair_dat30;
extern WMIM_DAT ch030_wmim_tbl[2];
extern WMIM mimacs_hair_dat39;
extern WMIM_DAT ch039_wmim_tbl[2];
extern float rope_vtx0[4];
extern ROPE_DAT rope_dat0;
extern float sudare_vtx0[4];
extern ROPE_DAT sudare_dat0;
extern float genkan_vtx000[4];
extern ROPE_DAT fr_genkan000;
extern float genkan_vtx001[4];
extern ROPE_DAT fr_genkan001;
extern float irori_vtx000[4];
extern ROPE_DAT fr_irori_dentou000;
extern float irori_vtx001[4];
extern ROPE_DAT fr_irori_dentou001;
extern float oozasiki_vtx000[4];
extern ROPE_DAT fr_oozasiki_dentou000;
extern float butuma_vtx000[4];
extern ROPE_DAT fr_butuma_dentou000;
extern float okunoma_vtx000[4];
extern ROPE_DAT fr_okunoma_dentou000;
extern float okunoma_vtx001[4];
extern ROPE_DAT fr_okunoma_dentou001;
extern float okunoma_vtx002[4];
extern ROPE_DAT fr_okunoma_sudare000;
extern ROPE_DAT fr_okunoma_sudare001;
extern ROPE_DAT fr_okunoma_sudare002;
extern float kyakuma_vtx000[4];
extern ROPE_DAT fr_kyakuma_dentou000;
extern float shouzi_vtx000[4];
extern ROPE_DAT fr_shouzi000;
extern float rry01_genkan_vtx[3][5];
extern ROPE_DAT fr_rry01_genkan_turi000;
extern ROPE_DAT fr_rry01_genkan_turi001;
extern ROPE_DAT fr_rry01_genkan_turi002;
extern float toumyou_vtx000[4];
extern ROPE_DAT fr_rry00_toumyou000;
extern ROPE_DAT fr_rry00_toumyou001;
extern float rkh00_vtx000[4];
extern float rkh00_vtx001[4];
extern float rkh00_vtx002[4];
extern ROPE_DAT fr_rkh00_rope001;
extern ROPE_DAT fr_rkh00_rope002;
extern ROPE_DAT fr_rkh00_rope003;
extern ROPE_DAT fr_rkh00_rope004;
extern float rtb08_vtx000[4];
extern ROPE_DAT fr_rtb08_dentou000;
extern float ry04_vtx000[4];
extern ROPE_DAT fr_ry04_tourou000;
extern ROPE_DAT fr_ry04_tourou001;
extern float ry02_vtx000[2][4];
extern ROPE_DAT fr_ry02_tourou000;
extern ROPE_DAT fr_ry02_tourou001;
extern ROPE_DAT fr_ry02_tourou002;
extern ROPE_DAT *rope_tbl[32];
extern CLOTH cloth_furisode3;
extern CLOTH furisode_mio;
extern CLOTH cloth_skirt;
extern CLOTH cloth_skirt_mio;
extern CLOTH cloth_skirt_mayu;
extern CLOTH cloth_skirt_miya;
extern CLOTH cloth_skirt_hako;
extern CLOTH cloth_skirt_manto_hako;
extern CLOTH cloth_manto_hako;
extern CLOTH cloth_manto_kusa1;
extern CLOTH cloth_manto_kusa2;
extern CLOTH cloth_skirt_kusa1;
extern CLOTH cloth_skirt_kusa2;
extern CLOTH cloth_manto_rakka1;
extern CLOTH cloth_manto_rakka2;
extern CLOTH cloth_skirt_rakka1;
extern CLOTH cloth_skirt_kubiore;
extern CLOTH cloth_manto_waninngyou;
extern CLOTH cloth_skirt_rakka2;
extern CLOTH cloth_skirt_kusakoro2;
extern CLOTH cloth_manto_noren;
extern CLOTH cloth_irori_noren;
extern CLOTH cloth_nuno_noren;
extern CLOTH cloth_nuno_nuno;
extern CLOTH cloth_genkan_noren;
extern CLOTH cloth_genkan_noren2;
extern CLOTH cloth_meian_noren;
extern CLOTH cloth_okunoma_sudare;
extern CLOTH cloth_meian_curtain;
extern CLOTH cloth_skirt_suisi;
extern CLOTH cloth_skirt_tama;
extern CLOTH cloth_skirt_yami2;
extern CLOTH cloth_skirt_sae;
extern CLOTH cloth_skirt_imi1;
extern CLOTH_DAT ch000_cloth[2];
extern COLLISION_DAT ch000_collision[4];
extern CLOTH_DAT ch001_cloth[2];
extern COLLISION_DAT ch001_collision[4];
extern CLOTH_DAT ch003_cloth[3];
extern float ch004_rist_vtx0[4][4];
extern float ch004_rist_vtx1[4][4];
extern CLOTH_DAT ch004_cloth[3];
extern float ch006_rist_vtx0[4][4];
extern float ch006_rist_vtx1[4][4];
extern CLOTH_DAT ch006_cloth[3];
extern COLLISION_DAT ch006_collision[2];
extern CLOTH_DAT ch011_cloth[3];
extern float ch013_rist_vtx0[4][4];
extern float ch013_rist_vtx1[4][4];
extern CLOTH_DAT ch013_cloth[4];
extern COLLISION_DAT ch013_collision[2];
extern CLOTH_DAT ch014_cloth[2];
extern CLOTH_DAT ch017_cloth[2];
extern COLLISION_DAT ch017_collision[4];
extern CLOTH_DAT ch018_cloth[6];
extern float ch019_rist_vtx0[4][4];
extern float ch019_rist_vtx1[4][4];
extern CLOTH_DAT ch019_cloth[3];
extern COLLISION_DAT ch019_collision[2];
extern float ch020_rist_vtx0[4][4];
extern float ch020_rist_vtx1[4][4];
extern CLOTH_DAT ch020_cloth[8];
extern COLLISION_DAT ch020_collision[3];
extern float ch021_rist_vtx0[4][4];
extern float ch021_rist_vtx1[4][4];
extern CLOTH_DAT ch021_cloth[4];
extern COLLISION_DAT ch021_collision[4];
extern float ch022_rist_vtx0[4][4];
extern float ch022_rist_vtx1[4][4];
extern CLOTH_DAT ch022_cloth[4];
extern COLLISION_DAT ch022_collision[4];
extern float ch024_rist_vtx0[4][4];
extern float ch024_rist_vtx1[4][4];
extern CLOTH_DAT ch024_cloth[5];
extern COLLISION_DAT ch024_collision[3];
extern float ch025_rist_vtx0[4][4];
extern float ch025_rist_vtx1[4][4];
extern CLOTH_DAT ch025_cloth[4];
extern COLLISION_DAT ch025_collision[2];
extern float ch026_rist_vtx0[4][4];
extern float ch026_rist_vtx1[4][4];
extern CLOTH_DAT ch026_cloth[3];
extern float ch027_rist_vtx0[4][4];
extern float ch027_rist_vtx1[4][4];
extern CLOTH_DAT ch027_cloth[3];
extern COLLISION_DAT ch027_collision[2];
extern float ch028_rist_vtx0[4][4];
extern float ch028_rist_vtx1[4][4];
extern CLOTH_DAT ch028_cloth[3];
extern COLLISION_DAT ch028_collision[2];
extern float ch029_rist_vtx0[4][4];
extern float ch029_rist_vtx1[4][4];
extern CLOTH_DAT ch029_cloth[3];
extern COLLISION_DAT ch029_collision[2];
extern CLOTH_DAT ch030_cloth[2];
extern COLLISION_DAT ch030_collision[6];
extern float ch031_rist_vtx0[4][4];
extern float ch031_rist_vtx1[4][4];
extern CLOTH_DAT ch031_cloth[3];
extern COLLISION_DAT ch031_collision[2];
extern CLOTH_DAT ch032_cloth[2];
extern float ch033_rist_vtx0[4][4];
extern float ch033_rist_vtx1[4][4];
extern CLOTH_DAT ch033_cloth[3];
extern COLLISION_DAT ch033_collision[2];
extern float ch038_rist_vtx0[4][4];
extern float ch038_rist_vtx1[4][4];
extern CLOTH_DAT ch038_cloth[3];
extern CLOTH_DAT ch039_cloth[3];
extern float ch041_rist_vtx0[4][4];
extern float ch041_rist_vtx1[4][4];
extern CLOTH_DAT ch041_cloth[3];
extern float ch043_rist_vtx0[4][4];
extern float ch043_rist_vtx1[4][4];
extern CLOTH_DAT ch043_cloth[3];
extern float ch044_rist_vtx0[4][4];
extern float ch044_rist_vtx1[4][4];
extern CLOTH_DAT ch044_cloth[3];
extern float ch047_rist_vtx0[4][4];
extern float ch047_rist_vtx1[4][4];
extern CLOTH_DAT ch047_cloth[3];
extern float ch048_rist_vtx0[4][4];
extern float ch048_rist_vtx1[4][4];
extern CLOTH_DAT ch048_cloth[3];
extern CLOTH_DAT ch049_cloth[3];
extern CLOTH_DAT ch053_cloth[2];
extern CLOTH_DAT ch055_cloth[2];
extern COLLISION_DAT ch055_collision[4];
extern float ch058_rist_vtx0[4][4];
extern float ch058_rist_vtx1[4][4];
extern CLOTH_DAT ch058_cloth[3];
extern float ch064_rist_vtx0[4][4];
extern float ch064_rist_vtx1[4][4];
extern CLOTH_DAT ch064_cloth[3];
extern float ch065_rist_vtx0[4][4];
extern float ch065_rist_vtx1[4][4];
extern CLOTH_DAT ch065_cloth[3];
extern float ch066_rist_vtx0[4][4];
extern float ch066_rist_vtx1[4][4];
extern CLOTH_DAT ch066_cloth[3];
extern float ch067_rist_vtx0[4][4];
extern float ch067_rist_vtx1[4][4];
extern CLOTH_DAT ch067_cloth[3];
extern float ch068_rist_vtx0[4][4];
extern float ch068_rist_vtx1[4][4];
extern CLOTH_DAT ch068_cloth[3];
extern float ch069_rist_vtx0[4][4];
extern float ch069_rist_vtx1[4][4];
extern CLOTH_DAT ch069_cloth[3];
extern float ch070_rist_vtx0[4][4];
extern float ch070_rist_vtx1[4][4];
extern CLOTH_DAT ch070_cloth[3];
extern float ch071_rist_vtx0[4][4];
extern float ch071_rist_vtx1[4][4];
extern CLOTH_DAT ch071_cloth[3];
extern float m999_rist_vtx0[4][4];
extern CLOTH_DAT m999_cloth[3];
extern COLLISION_DAT m999_collision[4];
extern CLOTH_DAT f000_cloth[2];
extern CLOTH_DAT fc_irori000[2];
extern CLOTH_DAT fc_irori001[2];
extern CLOTH_DAT fc_nuno000[2];
extern CLOTH_DAT fc_nuno001[2];
extern CLOTH_DAT fc_nuno002[2];
extern CLOTH_DAT fc_genkan000[2];
extern CLOTH_DAT fc_genkan001[2];
extern CLOTH_DAT fc_genkan002[2];
extern CLOTH_DAT fc_genkan003[2];
extern CLOTH_DAT fc_genkan004[2];
extern CLOTH_DAT fc_meian000[2];
extern CLOTH_DAT fc_meian001[2];
extern CLOTH_DAT fc_meian002[2];
extern CLOTH_DAT fc_meian003[2];
extern CLOTH_DAT fc_okunoma000[2];
extern CLOTH_DAT fc_meian004[2];
extern CLOTH_DAT fc_meian005[2];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_ACS_DAT_H
