// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_MIM_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_MIM_DAT_H


int mimdatGetMimeNo(ANI_CTRL *ani_ctrl, int num);

#endif // HOME_ZERO_ROM_ZERO2NP_SRC_GRAPHICS_MOTION_MIM_DAT_H
