// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H

void* malloc(size_t nbytes);
void free(void *aptr);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STDLIB_MALLOC_H
