// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRERROR_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRERROR_H

char* strerror(int errnum);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRERROR_H
