// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRRCHR_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRRCHR_H

char* strrchr(char *s, int i);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRRCHR_H
