// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRSTR_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRSTR_H

char* strstr(char *searchee, char *lookfor);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_STRSTR_H
