// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_U_STRERR_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_U_STRERR_H

char* _user_strerror(int errnum);

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_STRING_U_STRERR_H
