// STATUS: NOT STARTED

#ifndef USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H
#define USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H

int* __errno();

#endif // USR_LOCAL_SCE_EE_GCC_SRC_NEWLIB_LIBC_ERRNO_ERRNO_H
