// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_SAVE_LOAD_DAT_SAVE_LOAD_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_SAVE_LOAD_DAT_SAVE_LOAD_DAT_H

extern SPRT_DAT save_load_tex[60];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_SAVE_LOAD_DAT_SAVE_LOAD_DAT_H
