// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_GAMEOVER_PRG_GAMEOVER_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_GAMEOVER_PRG_GAMEOVER_DAT_H

extern SPRT_DAT gameover_tex[2];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_GAMEOVER_PRG_GAMEOVER_DAT_H
