// STATUS: NOT STARTED

#ifndef HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PUZZLE_PUZZLE_DAT_H
#define HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PUZZLE_PUZZLE_DAT_H

extern int pzl_conf_msg[6][2];


#endif // HOME_ZERO_ROM_ZERO2NP_SRC_INGAME_PUZZLE_PUZZLE_DAT_H
